#!/bin/bash

#
# Generate HTML pages from JSON metadata and markdown content.
# usage: ./gen_pages
#

set -Eeuxo pipefail

die() {
    echo "$@"
    exit 1
}

get_field() {
    jq --raw-output ".[\"$2\"]" <(echo "$1")
}

main () {
    local root="$(git rev-parse --show-toplevel)"
    local page_dir="$root/posts/pages"

    rm -rf "$page_dir"
    mkdir "$page_dir"

    while read meta; do
        echo "META:$meta"
        local author="$(get_field "$meta" "author")"
        local title="$(get_field "$meta" "title")"
        local post="$(get_field "$meta" "post")"
        local uploaded="$(get_field "$meta" "uploaded")"
        local last_updated="$(get_field "$meta" "last_updated")"
        local post_content="$(md2html "$post")" # TODO: actually escape post content?
        local filename="$(echo $title | tr ' ' '_' | tr '[:upper:]' '[:lower:]').html"
        local page="$root/posts/pages/$filename"

        sed "$root/posts/template/post.html" \
            -e "s/<!-- TITLE PLACEHOLDER -->/$title/" \
            -e "s/<!-- AUTHOR PLACEHOLDER -->/$author/" \
            -e "s/<!-- UPLOADED PLACEHOLDER -->/$uploaded/" \
            -e "s/<!-- UPDATED PLACEHOLDER -->/$last_updated/" \
            -e "s/<!-- POST PLACEHOLDER -->/THE POST LUL/" > "$page"

    done <<< "$(jq -c '.[]' "$root/posts/meta.json")"
}

main "$@"

