#!/bin/sh

# This is a wrapper script for entr to call

root="$(git rev-parse --show-toplevel)"
"$root/scripts/blog" gen_pages
"$root/scripts/blog" gen_homepage
"$root/scripts/blog" gen_blog_index
notify-send "gen_all_pages done"

